version: 3

# Source .env file(s)
dotenv: [.env]

env:
  DOCKER_IMAGE: 4lch4/shion-api
  DOCKER_CONTAINER_NAME: shion-api
  EXTERNAL_PORT: 4242
  INTERNAL_PORT: 8080

tasks:
  build:
    desc: Builds the project into a Docker image for use on the local architecture.
    aliases: [b]
    cmd: docker build -t ${DOCKER_IMAGE} .

  clean:
    deps: [stop]
    desc: Deletes the build output directory, any installed dependencies, any generated files, and any built Docker images.
    aliases: [c]
    cmd: docker rm ${DOCKER_CONTAINER_NAME}

  start:
    desc: Starts the project locally in a Docker container.
    aliases: [s, up]
    cmd: docker run -d -p ${EXTERNAL_PORT}:${INTERNAL_PORT} --env-file=.env --name ${DOCKER_CONTAINER_NAME} ${DOCKER_IMAGE}

  stop:
    desc: Stops the locally running Docker container.
    aliases: [st, down]
    cmd: docker stop ${DOCKER_CONTAINER_NAME}

  logs:
    desc: Tails the logs of the locally running Docker container.
    aliases: [l]
    cmd: docker logs -f ${DOCKER_CONTAINER_NAME}

  restart:
    desc: Rebuilds, stops, deletes, and starts the locally running Docker container.
    aliases: [r, reboot]
    cmds:
      - task build
      - task clean
      - task start
